package com.baystudio.droide.core

 
enum class AgentRequesterKind { PRIMARY, SUBAGENT }

// Subagent values are created by SubagentManager, never from model text.



data class AgentExecutionIdentity(
    val kind: AgentRequesterKind = AgentRequesterKind.PRIMARY,
    val agentType: String = "primary",
    val taskId: String = "",
    val parentSessionId: String = "",
    val depth: Int = 0,
) {
    init {
        require(depth >= 0) { "agent depth must be non-negative" }
        if (kind == AgentRequesterKind.SUBAGENT) {
            require(agentType.isNotBlank()) { "subagent type must not be blank" }
            require(taskId.isNotBlank()) { "subagent task id must not be blank" }
            require(parentSessionId.isNotBlank()) { "subagent parent session id must not be blank" }
        }
    }

    fun request(sessionId: String?): AgentRequestProvenance = AgentRequestProvenance(
        kind = kind,
        agentType = agentType,
        sessionId = sessionId.orEmpty(),
        parentSessionId = parentSessionId,
        taskId = taskId,
        depth = depth,
    )

    companion object {
        fun primary(): AgentExecutionIdentity = AgentExecutionIdentity()

        fun subagent(
            agentType: String,
            taskId: String,
            parentSessionId: String,
            depth: Int,
        ): AgentExecutionIdentity = AgentExecutionIdentity(
            kind = AgentRequesterKind.SUBAGENT,
            agentType = agentType,
            taskId = taskId,
            parentSessionId = parentSessionId,
            depth = depth,
        )
    }
}

 
data class AgentRequestProvenance(
    val kind: AgentRequesterKind = AgentRequesterKind.PRIMARY,
    val agentType: String = "primary",
    val sessionId: String = "",
    val parentSessionId: String = "",
    val taskId: String = "",
    val depth: Int = 0,
) {
    val isSubagent: Boolean get() = kind == AgentRequesterKind.SUBAGENT

    // Compact label deliberately generated by the harness so model-authored text cannot spoof origin.
    fun uiPrefix(): String {
        if (!isSubagent) return ""
        val safeType = agentType.filter { it.isLetterOrDigit() || it in "._-" }.take(24).ifBlank { "subagent" }
        val safeTask = taskId.filter { it.isLetterOrDigit() || it in "._-" }.take(8).ifBlank { "unknown" }
        return "[$safeType#$safeTask]"
    }

    fun decorateSummary(summary: String): String =
        if (isSubagent) "${uiPrefix()} ${summary.trim()}".take(240) else summary

    fun decorateHeader(header: String): String =
        if (isSubagent) "${uiPrefix()} ${header.trim()}".take(40) else header.take(40)

    companion object {
        fun primary(sessionId: String = ""): AgentRequestProvenance = AgentRequestProvenance(sessionId = sessionId)
    }
}
