#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

fail() { echo "RELEASE_SOURCE_FAILED: $*" >&2; exit 1; }

[[ -x ./gradlew ]] || fail "gradlew is not executable"
[[ -f gradle/wrapper/gradle-wrapper.jar ]] || fail "missing gradle-wrapper.jar"

if find . -path './.git' -prune -o -type f \
  \( -name '*.apk' -o -name '*.aab' -o -name '*.jks' -o -name '*.keystore' -o -name '*.p12' -o -name '.env' -o -name 'auth.json' \) \
  -print -quit | grep -q .; then fail "generated binary or credential material present"; fi

if find . -path './.git' -prune -o -type d \
  \( -name build -o -name .gradle -o -name .idea -o -name __pycache__ -o -name .pytest_cache \) \
  -print -quit | grep -q .; then fail "build/cache directory present"; fi

# Internal milestone/recovery vocabulary must not leak into the public source tree.
if find . -path './.git' -prune -o -type f -print | grep -Ei '(^|/)(cp[0-9]|checkpoint|recovery[-_]|continuation|progress_cp)' >/tmp/droide-release-name-hit; then
  cat /tmp/droide-release-name-hit >&2; fail "internal history artifact filename detected"; fi
milestone_pattern='[Cc][Pp]''[0-9]{1,3}[A-Za-z0-9_-]*'
recovery_pattern='recovery-''08[a-z0-9_-]*'
generation_pattern='generated by (A''I|ChatGPT|Claude|Gemini|Copilot)|A''I-generated'
if grep -RInE --exclude-dir=.git --exclude='*.jar' --exclude='*.aar' --exclude='*.so' --exclude='*.png' \
  "${milestone_pattern}|${recovery_pattern}|${generation_pattern}" . \
  >/tmp/droide-release-residue-hit 2>/dev/null; then
  cat /tmp/droide-release-residue-hit >&2; fail "internal milestone or generation residue detected"; fi

if grep -RInE --exclude-dir=.git --exclude='*.md' \
  '(sk-[A-Za-z0-9_-]{20,}|AIza[0-9A-Za-z_-]{20,}|ghp_[0-9A-Za-z]{20,})' . \
  >/tmp/droide-release-secret-hit 2>/dev/null; then
  cat /tmp/droide-release-secret-hit >&2; fail "credential signature detected"; fi

python3 tools/verify_dependency_policy.py
python3 tools/verify_third_party_integrity.py
python3 tools/verify_runtime_licenses.py
python3 tools/verify_termux_provenance.py
echo RELEASE_SOURCE_VERIFICATION_OK
